# Generated by Django 5.2.8 on 2025-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option C', 'Option C'), ('Option A ', 'Option A'), ('Option D', 'Option D'), ('Option B', 'Option B')], max_length=10),
        ),
    ]
