# Generated by Django 5.2.8 on 2025-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
